INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x00", 'Sem Falha');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x01", 'Falha sequência de fases');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x02", 'Falha sobrecorrente motor elétrico');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x03", 'Falha sobrecorrente ventilador');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x04", 'Falha temperatura alta de saída do ar');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x05", 'Falha temperatura alta do óleo');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x06", 'Falha temperatura alta do ponto de orvalho');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x07", 'Falha sensor TS');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x08", 'Falha sensor TO');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x09", 'Falha sensor TPO');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0A", 'Falha sensor Tamb');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0B", 'Falha sensor P1');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0C", 'N/D');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0D", 'Falha sobrecorrente secador integrado');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0E", 'Falha pressão alta - secador integrado');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x0F", 'Falha pressão baixa - secador integrado');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x10", 'Falha pressão baixa linha de ar comprimido');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x11", 'Falha pressão alta linha de ar comprimido');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x12", 'Alerta 1ª troca de filtro');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x13", 'Alerta troca de óleo');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x14", 'Alerta troca filtro óleo');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x15", 'Alerta troca filtro separador');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x16", 'Alerta troca filtro de ar');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x17", 'Alerta troca correias');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x18", 'Alerta limpeza resfriador ar/óleo');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x19", 'Alerta revisão geral unidade compressora');
INSERT INTO compressor_db.falha (id, descricao) VALUES ("0x1A", 'Alerta elemento coalescente saturado (secador integrado)');